parameters:
#    crm_invoice.example.class: Crm\InvoiceBundle\Example

services:
#    crm_invoice.example:
#        class: %crm_invoice.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
